MAX_CAPABILITY_EXECUTION_MS = 30 * 60 * 1000
CONTENT_PRODUCTION_TOTAL_TIMEOUT_MS = MAX_CAPABILITY_EXECUTION_MS
CONTENT_PRODUCTION_INACTIVITY_TIMEOUT_MS = 10 * 60 * 1000
IMAGE_GENERATION_TOTAL_TIMEOUT_MS = MAX_CAPABILITY_EXECUTION_MS
IMAGE_GENERATION_INACTIVITY_TIMEOUT_MS = 10 * 60 * 1000
PRESENTATION_CREATION_TOTAL_TIMEOUT_MS = MAX_CAPABILITY_EXECUTION_MS
PRESENTATION_CREATION_INACTIVITY_TIMEOUT_MS = 10 * 60 * 1000


__all__ = [
    "CONTENT_PRODUCTION_INACTIVITY_TIMEOUT_MS",
    "CONTENT_PRODUCTION_TOTAL_TIMEOUT_MS",
    "IMAGE_GENERATION_INACTIVITY_TIMEOUT_MS",
    "IMAGE_GENERATION_TOTAL_TIMEOUT_MS",
    "PRESENTATION_CREATION_INACTIVITY_TIMEOUT_MS",
    "PRESENTATION_CREATION_TOTAL_TIMEOUT_MS",
    "MAX_CAPABILITY_EXECUTION_MS",
]
