FROM node:20-slim AS build

WORKDIR /app

ARG VITE_ADMIN_WEB_URL
ENV VITE_ADMIN_WEB_URL=$VITE_ADMIN_WEB_URL

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.29.8-alpine

RUN apk upgrade --no-cache

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
